from enum import Enum


class TelloActionType(Enum):
    SET_FORWARD_VELOCITY = 1
    SET_BACKWARD_VELOCITY = 2
    SET_LEFT_VELOCITY = 3
    SET_RIGHT_VELOCITY = 4
    SET_UP_VELOCITY = 5
    SET_DOWN_VELOCITY = 6
    SET_YAW_CLOCKWISE_VELOCITY = 7
    SET_YAW_COUNTER_CLOCKWISE_VELOCITY = 8
    TAKEOFF = 9
    LAND = 10
